### ISSUE TITLE
yttadd ignores duration and always add 1h

### ISSUE THREAD

**Issue by sikmir** [bullshitsoftware/youtimetrack#1]
https://github.com/bullshitsoftware/youtimetrack/blob/2b8b4d2e56c2ab6f41ad510c767bd3d95fec38bc/internal/pkg/youtrack/youtrack.go#L109-L114

**Comment by bullshitsoftware** [comment]
Fixed in v0.1.1

**Comment by sikmir** [comment]
Thanks!
